// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     restaurant_approval_response.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type OrderApprovalStatus int32

const (
	OrderApprovalStatusAPPROVED OrderApprovalStatus = 0
	OrderApprovalStatusREJECTED OrderApprovalStatus = 1
)

func (e OrderApprovalStatus) String() string {
	switch e {
	case OrderApprovalStatusAPPROVED:
		return "APPROVED"
	case OrderApprovalStatusREJECTED:
		return "REJECTED"
	}
	return "unknown"
}

func writeOrderApprovalStatus(r OrderApprovalStatus, w io.Writer) error {
	return vm.WriteInt(int32(r), w)
}

func NewOrderApprovalStatusValue(raw string) (r OrderApprovalStatus, err error) {
	switch raw {
	case "APPROVED":
		return OrderApprovalStatusAPPROVED, nil
	case "REJECTED":
		return OrderApprovalStatusREJECTED, nil
	}

	return -1, fmt.Errorf("invalid value for OrderApprovalStatus: '%s'", raw)

}

func (b OrderApprovalStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(b.String())
}

func (b *OrderApprovalStatus) UnmarshalJSON(data []byte) error {
	var stringVal string
	err := json.Unmarshal(data, &stringVal)
	if err != nil {
		return err
	}
	val, err := NewOrderApprovalStatusValue(stringVal)
	*b = val
	return err
}

type OrderApprovalStatusWrapper struct {
	Target *OrderApprovalStatus
}

func (b OrderApprovalStatusWrapper) SetBoolean(v bool) {
	panic("Unable to assign boolean to int field")
}

func (b OrderApprovalStatusWrapper) SetInt(v int32) {
	*(b.Target) = OrderApprovalStatus(v)
}

func (b OrderApprovalStatusWrapper) SetLong(v int64) {
	panic("Unable to assign long to int field")
}

func (b OrderApprovalStatusWrapper) SetFloat(v float32) {
	panic("Unable to assign float to int field")
}

func (b OrderApprovalStatusWrapper) SetUnionElem(v int64) {
	panic("Unable to assign union elem to int field")
}

func (b OrderApprovalStatusWrapper) SetDouble(v float64) {
	panic("Unable to assign double to int field")
}

func (b OrderApprovalStatusWrapper) SetBytes(v []byte) {
	panic("Unable to assign bytes to int field")
}

func (b OrderApprovalStatusWrapper) SetString(v string) {
	panic("Unable to assign string to int field")
}

func (b OrderApprovalStatusWrapper) Get(i int) types.Field {
	panic("Unable to get field from int field")
}

func (b OrderApprovalStatusWrapper) SetDefault(i int) {
	panic("Unable to set default on int field")
}

func (b OrderApprovalStatusWrapper) AppendMap(key string) types.Field {
	panic("Unable to append map key to from int field")
}

func (b OrderApprovalStatusWrapper) AppendArray() types.Field {
	panic("Unable to append array element to from int field")
}

func (b OrderApprovalStatusWrapper) NullField(int) {
	panic("Unable to null field in int field")
}

func (b OrderApprovalStatusWrapper) HintSize(int) {
	panic("Unable to hint size in int field")
}

func (b OrderApprovalStatusWrapper) Finalize() {}
