// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     payment_request.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type PaymentRequestAvroModel struct {
	Id string `json:"id"`

	SagaId string `json:"sagaId"`

	CustomerId string `json:"customerId"`

	OrderId string `json:"orderId"`

	Price Bytes `json:"price"`

	CreatedAt int64 `json:"createdAt"`

	PaymentOrderStatus PaymentOrderStatus `json:"paymentOrderStatus"`
}

const PaymentRequestAvroModelAvroCRC64Fingerprint = "\xdfrD5\xe12\xc7\x13"

func NewPaymentRequestAvroModel() PaymentRequestAvroModel {
	r := PaymentRequestAvroModel{}
	return r
}

func DeserializePaymentRequestAvroModel(r io.Reader) (PaymentRequestAvroModel, error) {
	t := NewPaymentRequestAvroModel()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializePaymentRequestAvroModelFromSchema(r io.Reader, schema string) (PaymentRequestAvroModel, error) {
	t := NewPaymentRequestAvroModel()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writePaymentRequestAvroModel(r PaymentRequestAvroModel, w io.Writer) error {
	var err error
	err = vm.WriteString(r.Id, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.SagaId, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.CustomerId, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.OrderId, w)
	if err != nil {
		return err
	}
	err = vm.WriteBytes(r.Price, w)
	if err != nil {
		return err
	}
	err = vm.WriteLong(r.CreatedAt, w)
	if err != nil {
		return err
	}
	err = writePaymentOrderStatus(r.PaymentOrderStatus, w)
	if err != nil {
		return err
	}
	return err
}

func (r PaymentRequestAvroModel) Serialize(w io.Writer) error {
	return writePaymentRequestAvroModel(r, w)
}

func (r PaymentRequestAvroModel) Schema() string {
	return "{\"fields\":[{\"name\":\"id\",\"type\":{\"logicalType\":\"uuid\",\"type\":\"string\"}},{\"name\":\"sagaId\",\"type\":{\"logicalType\":\"uuid\",\"type\":\"string\"}},{\"name\":\"customerId\",\"type\":{\"logicalType\":\"uuid\",\"type\":\"string\"}},{\"name\":\"orderId\",\"type\":{\"logicalType\":\"uuid\",\"type\":\"string\"}},{\"name\":\"price\",\"type\":{\"logicalType\":\"decimal\",\"precision\":10,\"scale\":2,\"type\":\"bytes\"}},{\"name\":\"createdAt\",\"type\":{\"logicalType\":\"timestamp-millis\",\"type\":\"long\"}},{\"name\":\"paymentOrderStatus\",\"type\":{\"name\":\"PaymentOrderStatus\",\"symbols\":[\"PENDING\",\"CANCELLED\"],\"type\":\"enum\"}}],\"name\":\"com.food.ordering.system.kafka.order.avro.model.PaymentRequestAvroModel\",\"type\":\"record\"}"
}

func (r PaymentRequestAvroModel) SchemaName() string {
	return "com.food.ordering.system.kafka.order.avro.model.PaymentRequestAvroModel"
}

func (_ PaymentRequestAvroModel) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ PaymentRequestAvroModel) SetInt(v int32)       { panic("Unsupported operation") }
func (_ PaymentRequestAvroModel) SetLong(v int64)      { panic("Unsupported operation") }
func (_ PaymentRequestAvroModel) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ PaymentRequestAvroModel) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ PaymentRequestAvroModel) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ PaymentRequestAvroModel) SetString(v string)   { panic("Unsupported operation") }
func (_ PaymentRequestAvroModel) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *PaymentRequestAvroModel) Get(i int) types.Field {
	switch i {
	case 0:
		w := types.String{Target: &r.Id}

		return w

	case 1:
		w := types.String{Target: &r.SagaId}

		return w

	case 2:
		w := types.String{Target: &r.CustomerId}

		return w

	case 3:
		w := types.String{Target: &r.OrderId}

		return w

	case 4:
		w := BytesWrapper{Target: &r.Price}

		return w

	case 5:
		w := types.Long{Target: &r.CreatedAt}

		return w

	case 6:
		w := PaymentOrderStatusWrapper{Target: &r.PaymentOrderStatus}

		return w

	}
	panic("Unknown field index")
}

func (r *PaymentRequestAvroModel) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *PaymentRequestAvroModel) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ PaymentRequestAvroModel) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ PaymentRequestAvroModel) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ PaymentRequestAvroModel) HintSize(int)                     { panic("Unsupported operation") }
func (_ PaymentRequestAvroModel) Finalize()                        {}

func (_ PaymentRequestAvroModel) AvroCRC64Fingerprint() []byte {
	return []byte(PaymentRequestAvroModelAvroCRC64Fingerprint)
}

func (r PaymentRequestAvroModel) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["id"], err = json.Marshal(r.Id)
	if err != nil {
		return nil, err
	}
	output["sagaId"], err = json.Marshal(r.SagaId)
	if err != nil {
		return nil, err
	}
	output["customerId"], err = json.Marshal(r.CustomerId)
	if err != nil {
		return nil, err
	}
	output["orderId"], err = json.Marshal(r.OrderId)
	if err != nil {
		return nil, err
	}
	output["price"], err = json.Marshal(r.Price)
	if err != nil {
		return nil, err
	}
	output["createdAt"], err = json.Marshal(r.CreatedAt)
	if err != nil {
		return nil, err
	}
	output["paymentOrderStatus"], err = json.Marshal(r.PaymentOrderStatus)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *PaymentRequestAvroModel) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["id"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Id); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for id")
	}
	val = func() json.RawMessage {
		if v, ok := fields["sagaId"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.SagaId); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for sagaId")
	}
	val = func() json.RawMessage {
		if v, ok := fields["customerId"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.CustomerId); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for customerId")
	}
	val = func() json.RawMessage {
		if v, ok := fields["orderId"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.OrderId); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for orderId")
	}
	val = func() json.RawMessage {
		if v, ok := fields["price"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Price); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for price")
	}
	val = func() json.RawMessage {
		if v, ok := fields["createdAt"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.CreatedAt); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for createdAt")
	}
	val = func() json.RawMessage {
		if v, ok := fields["paymentOrderStatus"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.PaymentOrderStatus); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for paymentOrderStatus")
	}
	return nil
}
