// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     payment_request.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type PaymentOrderStatus int32

const (
	PaymentOrderStatusPENDING   PaymentOrderStatus = 0
	PaymentOrderStatusCANCELLED PaymentOrderStatus = 1
)

func (e PaymentOrderStatus) String() string {
	switch e {
	case PaymentOrderStatusPENDING:
		return "PENDING"
	case PaymentOrderStatusCANCELLED:
		return "CANCELLED"
	}
	return "unknown"
}

func writePaymentOrderStatus(r PaymentOrderStatus, w io.Writer) error {
	return vm.WriteInt(int32(r), w)
}

func NewPaymentOrderStatusValue(raw string) (r PaymentOrderStatus, err error) {
	switch raw {
	case "PENDING":
		return PaymentOrderStatusPENDING, nil
	case "CANCELLED":
		return PaymentOrderStatusCANCELLED, nil
	}

	return -1, fmt.Errorf("invalid value for PaymentOrderStatus: '%s'", raw)

}

func (b PaymentOrderStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(b.String())
}

func (b *PaymentOrderStatus) UnmarshalJSON(data []byte) error {
	var stringVal string
	err := json.Unmarshal(data, &stringVal)
	if err != nil {
		return err
	}
	val, err := NewPaymentOrderStatusValue(stringVal)
	*b = val
	return err
}

type PaymentOrderStatusWrapper struct {
	Target *PaymentOrderStatus
}

func (b PaymentOrderStatusWrapper) SetBoolean(v bool) {
	panic("Unable to assign boolean to int field")
}

func (b PaymentOrderStatusWrapper) SetInt(v int32) {
	*(b.Target) = PaymentOrderStatus(v)
}

func (b PaymentOrderStatusWrapper) SetLong(v int64) {
	panic("Unable to assign long to int field")
}

func (b PaymentOrderStatusWrapper) SetFloat(v float32) {
	panic("Unable to assign float to int field")
}

func (b PaymentOrderStatusWrapper) SetUnionElem(v int64) {
	panic("Unable to assign union elem to int field")
}

func (b PaymentOrderStatusWrapper) SetDouble(v float64) {
	panic("Unable to assign double to int field")
}

func (b PaymentOrderStatusWrapper) SetBytes(v []byte) {
	panic("Unable to assign bytes to int field")
}

func (b PaymentOrderStatusWrapper) SetString(v string) {
	panic("Unable to assign string to int field")
}

func (b PaymentOrderStatusWrapper) Get(i int) types.Field {
	panic("Unable to get field from int field")
}

func (b PaymentOrderStatusWrapper) SetDefault(i int) {
	panic("Unable to set default on int field")
}

func (b PaymentOrderStatusWrapper) AppendMap(key string) types.Field {
	panic("Unable to append map key to from int field")
}

func (b PaymentOrderStatusWrapper) AppendArray() types.Field {
	panic("Unable to append array element to from int field")
}

func (b PaymentOrderStatusWrapper) NullField(int) {
	panic("Unable to null field in int field")
}

func (b PaymentOrderStatusWrapper) HintSize(int) {
	panic("Unable to hint size in int field")
}

func (b PaymentOrderStatusWrapper) Finalize() {}
