// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     payment_response.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/container"
	"github.com/actgardner/gogen-avro/v10/vm"
)

func NewPaymentResponseAvroModelWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := NewPaymentResponseAvroModel()
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

// container reader
type PaymentResponseAvroModelReader struct {
	r io.Reader
	p *vm.Program
}

func NewPaymentResponseAvroModelReader(r io.Reader) (*PaymentResponseAvroModelReader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewPaymentResponseAvroModel()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &PaymentResponseAvroModelReader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r PaymentResponseAvroModelReader) Read() (PaymentResponseAvroModel, error) {
	t := NewPaymentResponseAvroModel()
	err := vm.Eval(r.r, r.p, &t)
	return t, err
}
