// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     restaurant_approval_request.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/container"
	"github.com/actgardner/gogen-avro/v10/vm"
)

func NewProductWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := NewProduct()
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

// container reader
type ProductReader struct {
	r io.Reader
	p *vm.Program
}

func NewProductReader(r io.Reader) (*ProductReader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewProduct()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &ProductReader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r ProductReader) Read() (Product, error) {
	t := NewProduct()
	err := vm.Eval(r.r, r.p, &t)
	return t, err
}
