// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     restaurant_approval_request.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type Product struct {
	Id string `json:"id"`

	Quantity int32 `json:"quantity"`
}

const ProductAvroCRC64Fingerprint = "\xf7\xb6\xeb@\xfc7\xa2\xa5"

func NewProduct() Product {
	r := Product{}
	return r
}

func DeserializeProduct(r io.Reader) (Product, error) {
	t := NewProduct()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeProductFromSchema(r io.Reader, schema string) (Product, error) {
	t := NewProduct()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeProduct(r Product, w io.Writer) error {
	var err error
	err = vm.WriteString(r.Id, w)
	if err != nil {
		return err
	}
	err = vm.WriteInt(r.Quantity, w)
	if err != nil {
		return err
	}
	return err
}

func (r Product) Serialize(w io.Writer) error {
	return writeProduct(r, w)
}

func (r Product) Schema() string {
	return "{\"fields\":[{\"logicalType\":\"uuid\",\"name\":\"id\",\"type\":\"string\"},{\"name\":\"quantity\",\"type\":\"int\"}],\"name\":\"com.food.ordering.system.kafka.order.avro.model.Product\",\"type\":\"record\"}"
}

func (r Product) SchemaName() string {
	return "com.food.ordering.system.kafka.order.avro.model.Product"
}

func (_ Product) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ Product) SetInt(v int32)       { panic("Unsupported operation") }
func (_ Product) SetLong(v int64)      { panic("Unsupported operation") }
func (_ Product) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ Product) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ Product) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ Product) SetString(v string)   { panic("Unsupported operation") }
func (_ Product) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *Product) Get(i int) types.Field {
	switch i {
	case 0:
		w := types.String{Target: &r.Id}

		return w

	case 1:
		w := types.Int{Target: &r.Quantity}

		return w

	}
	panic("Unknown field index")
}

func (r *Product) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *Product) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ Product) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ Product) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ Product) HintSize(int)                     { panic("Unsupported operation") }
func (_ Product) Finalize()                        {}

func (_ Product) AvroCRC64Fingerprint() []byte {
	return []byte(ProductAvroCRC64Fingerprint)
}

func (r Product) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["id"], err = json.Marshal(r.Id)
	if err != nil {
		return nil, err
	}
	output["quantity"], err = json.Marshal(r.Quantity)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *Product) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["id"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Id); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for id")
	}
	val = func() json.RawMessage {
		if v, ok := fields["quantity"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Quantity); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for quantity")
	}
	return nil
}
