// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     restaurant_approval_request.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/container"
	"github.com/actgardner/gogen-avro/v10/vm"
)

func NewRestaurantApprovalRequestAvroModelWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := NewRestaurantApprovalRequestAvroModel()
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

// container reader
type RestaurantApprovalRequestAvroModelReader struct {
	r io.Reader
	p *vm.Program
}

func NewRestaurantApprovalRequestAvroModelReader(r io.Reader) (*RestaurantApprovalRequestAvroModelReader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewRestaurantApprovalRequestAvroModel()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &RestaurantApprovalRequestAvroModelReader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r RestaurantApprovalRequestAvroModelReader) Read() (RestaurantApprovalRequestAvroModel, error) {
	t := NewRestaurantApprovalRequestAvroModel()
	err := vm.Eval(r.r, r.p, &t)
	return t, err
}
