// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     restaurant_approval_response.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/container"
	"github.com/actgardner/gogen-avro/v10/vm"
)

func NewRestaurantApprovalResponseAvroModelWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := NewRestaurantApprovalResponseAvroModel()
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

// container reader
type RestaurantApprovalResponseAvroModelReader struct {
	r io.Reader
	p *vm.Program
}

func NewRestaurantApprovalResponseAvroModelReader(r io.Reader) (*RestaurantApprovalResponseAvroModelReader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewRestaurantApprovalResponseAvroModel()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &RestaurantApprovalResponseAvroModelReader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r RestaurantApprovalResponseAvroModelReader) Read() (RestaurantApprovalResponseAvroModel, error) {
	t := NewRestaurantApprovalResponseAvroModel()
	err := vm.Eval(r.r, r.p, &t)
	return t, err
}
